org: lcsfrancoltda # Your organizationhere
service: sls-setup # Your service name here

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${ opt:stage, 'dev' }
  environment: ${file(./sls/config/env.yml)}
  iam:
    role: ${file(./sls/config/role.yml)}

custom:
  cognito:
    PoolName: ${self:service}-${self:provider.stage}-UserPool

package:
  individually: true

build:
  esbuild:
    configFile: esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
  - ${file(./sls/resources/MainTable.yml)}
