export enum ErrorCode {
  // APP
  VALIDATION = "VALIDATION",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_CONFIRMATION_CODE = "INVALID_CONFIRMATION_CODE",

  // HTTP
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
